name: py-check
on:
  push:
    branches:
      - main
    tags:

jobs:
  publish:
    name: publish
    run-on: ubuntu-latest
    environment: main
    steps:
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
